# Generated by Django 3.2.23 on 2024-02-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('marketing', models.CharField(choices=[('sales', 'Sales'), ('careers', 'Careers'), ('others', 'Others')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
